databases:
  - name: notes-db
    databaseName: notesdb
    user: notesuser

services:
  - type: web
    name: notes-backend
    env: java
    plan: free
    branch: main
    rootDir: .
    buildCommand: ./mvnw clean install
    startCommand: java -Dspring.profiles.active=postgres -jar target/notes-app-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: notes-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: notes-db
          property: password
