version: "1"

databases:
  - name: notes-db
    databaseName: notesdb
    user: notesuser

services:
  - type: web
    name: notes-backend
    env: docker
    plan: free
    branch: main
    rootDir: notes-backend
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: notes-db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: notes-db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: notes-db
          property: password
